### ISSUE TITLE
Weird Giant Mario glitch that appears on every Sky Secret Level

### ISSUE THREAD

**Issue by Jayacheal** [JoshuaMKW/BetterSunshineEngine#17]
Mario's collision is also big, not just his model, which makes some sky levels impossible to beat, FLUDD is also glitched.
[video of the glitch](https://youtu.be/ZLDoRQQEoCo?si=AFaNmKev4HAJsX5H&t=50)

**Comment by JoshuaMKW** [comment]
Hello Jayacheal. This is indeed a bug, it is an interesting one because it actually is "correct" behavior (disregarding the visual oddities of Mario's mesh due to the bones, and the obviously incorrect rotation of FLUDD). Basically, Better Sunshine Engine has code to let you scale the player controller to different sizes, and this ends up causing secret courses to bug out. The reason for this is that, interestingly enough, Nintendo set the player scale of secret courses to 4x, if I remember correctly. The only reason you don't see this in the base game is because Nintendo disabled player scaling.

Is this a remnant of a potential beta feature? Possibly. However since it keeps causing problems and Better Sunshine Engine isn't supposed to be opinionated anyway, it's probably best I remove it entirely. Especially since it is incomplete anyway.

In the next release of Better Sunshine Engine, I'll have this fully addressed.
