### ISSUE TITLE
Playing with 60 FPS, sometimes the music gets stuck on the first note

### ISSUE THREAD

**Issue by Jayacheal** [JoshuaMKW/BetterSunshineEngine#18]
this error also occurs when using the 60 fps gecko code for the original rom so I wonder if it's fixable or not.

**Comment by JoshuaMKW** [comment]
It's not easily fixable; this digs deep into the internals of the JAudio engine, which I am unfamiliar with. I honestly couldn't say for sure why this happens, but it seems to be pretty infrequent. Since the Japanese revision of Sunshine has the infamous audio bug that kills speedruns, I'd posit that the audio engine itself is just fundamentally unstable in some way.

That being said, I currently don't have plans to investigate or remedy this, so I'm closing the issue until further notice.
